### ISSUE TITLE
Control routing through implementations via header?

### ISSUE THREAD

**Issue by robbkidd** [honeycombio/example-greeting-service#23]
Would be cool to be able to select which language implementations a request is routed to by setting something in the request. Parameters? Headers?

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
