### ISSUE TITLE
Something in trace data to record a routing decision?

### ISSUE THREAD

**Issue by robbkidd** [honeycombio/example-greeting-service#24]
With a load balancer for each named microservice load-balancing across the various language implementation of that microservice, it would be helpful to see in the trace data which of the microservice backends was selected for a particular trace. Otherwise, if there is a problem with telemetry emitting from a YEAR microservice, the HTTP GET from one service to `http://year` won't indicate _which_ year implementation is having trouble.

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
