### ISSUE TITLE
Kubify running all the things!

### ISSUE THREAD

**Issue by robbkidd** [honeycombio/example-greeting-service#26]
There's [a branch in-flight using kustomize YAML](https://github.com/honeycombio/example-greeting-service/tree/robb.kubify) for all the microservices, kube Services to load-balance in front of them, and to run an OTel Collector.

Maybe helm charts would be better, especially considering the amount of duplication in the deployment definitions for each type of microservice.

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
